name: 'CodeBunny AI Review'
description: 'AI-powered code reviews using Continue Agent on pull requests'
author: 'Brian Douglas'
inputs:
  continue-api-key:
    description: 'API key for Continue service'
    required: true
  github-token:
    description: 'GitHub token for API access (defaults to GITHUB_TOKEN if not provided)'
    required: false
    default: ''
  continue-org:
    description: 'Continue organization/username from Continue Hub'
    required: true
  continue-config:
    description: 'Continue assistant path (format: username/assistant-name)'
    required: true
  enable-prisma-storage:
    description: 'Enable Prisma Postgres storage for unlimited review history (optional)'
    required: false
    default: 'false'
  database-url:
    description: 'Prisma Postgres or Postgres connection string (maps to DATABASE_URL)'
    required: false
    default: ''
  direct-database-url:
    description: 'Direct Postgres connection string for migrations (maps to DIRECT_DATABASE_URL)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Continue CLI
      shell: bash
      run: |
        echo "Installing Continue CLI..."
        # Install locally in action directory
        cd ${{ github.action_path }}
        npm install @continuedev/cli@1.4.30
        # Add to PATH
        echo "${{ github.action_path }}/node_modules/.bin" >> $GITHUB_PATH

    - name: Install action dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "Installing action dependencies..."
        npm init -y
        npm install @actions/core @actions/github @actions/exec @actions/artifact js-yaml glob @octokit/rest @prisma/client @prisma/adapter-neon
        npm install --save-dev @types/js-yaml @types/node typescript tsx prisma

    - name: Run CodeBunny Review
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        CONTINUE_API_KEY: ${{ inputs.continue-api-key }}
        CONTINUE_ORG: ${{ inputs.continue-org }}
        CONTINUE_CONFIG: ${{ inputs.continue-config }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_CONTINUE_API_KEY: ${{ inputs.continue-api-key }}
        INPUT_CONTINUE_ORG: ${{ inputs.continue-org }}
        INPUT_CONTINUE_CONFIG: ${{ inputs.continue-config }}
        INPUT_ENABLE_PRISMA_STORAGE: ${{ inputs.enable-prisma-storage }}
        DATABASE_URL: ${{ inputs.database-url }}
        DIRECT_DATABASE_URL: ${{ inputs.direct-database-url }}
      run: |
        echo "Running CodeBunny Review..."
        npx tsx index.ts

branding:
  icon: 'code'
  color: 'blue'
